### ISSUE TITLE
Products to Calendar?

### ISSUE THREAD

**Issue by audriejurgens** [andresmrg/local_coursetocal#1]
Hi Andres,
Thanks for this plugin!  We needed a way to let our customers choose courses from a calendar as well as a catalogue.  We use the Intellicart plugin to sell our courses.  Is there a way to have the link take the user to the Intellicart product that contains the course so the user can buy it instead of straight to the course?
Thanks,
Audrie

**Comment by andresmrg** [comment]
Hello,

The easiest way would be to add the link to the summary of the course using the HTML editor. Also, you may want to remove a variable in the code `$linkurl` within the locallib.php file so it doesn't display the link to take users to the course anymore. You should look for a line of code like the one mention below and remove `$linkurl`.

`$details->summary . "<br>" . $summaryfile . $linkurl;`

Let me know if that helps.

**Comment by audriejurgens** [comment]
Great! I've already added the link in the HTML editor and I'll ask our hosted Moodle provider to remove the variable.

**Comment by andresmrg** [comment]
Great! Keep in mind that line is present in all functions in that file. I'm glad that helps.
