### ISSUE TITLE
Compatible with 3.8+?

### ISSUE THREAD

**Issue by argwallace** [andresmrg/local_coursetocal#2]
Hello.

Has compatibility for 3.8+ been achieved for this plugin yet? The plugin seems to be working in regards to its functionality. However, when I make some general settings changes and need to upgrade the moodle database, it appears that the refresh page gets stuck on the Course to Calendar settings saved screen. I have to navigate back to the main URL for the site. I am attaching the screen that won't dismiss.

<img width="1178" alt="Screen Shot 2020-06-26 at 2 36 20 PM" src="https://user-images.githubusercontent.com/65811524/85853045-7dc3b780-b7ba-11ea-89b3-8ba84eff847f.png">

Stephen

**Comment by andresmrg** [comment]
Hi @argwallace ... I am preparing a new release and will be sent as soon as it is fully tested. Do you have any email that would like to get notify directly? I will also update this issue.

**Comment by argwallace** [comment]
Thanks!

Yes you can send it to this address: stephen.wallace(at) mac.com

Thanks,
Stephen

**Comment by lmsdoctor** [comment]
Stephen, I've sent an update via email. Confirm everything works as expected to close this issue. If there is something else, please add a new issue!

Thanks,

**Comment by argwallace** [comment]
Hey! I have tried this newer version and unfortunately the issue persists. It installs fine but after completing the installation process, it still gets caught in this Settings loop as before.

**Comment by andresmrg** [comment]
The issue was resolved as the system needed to have at least 1 visible category for the settings to function properly.
